name: megahackdesafioolist
description: App desenvolvido durante a Hackaton MegaHack - Desafio Olist

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  google_sign_in: ^4.1.0
  splashscreen: ^1.2.0
  cached_network_image: ^2.2.0
  rxdart: ^0.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/img_bot_first.png
    - assets/images/bot_icon.png
    - assets/images/bot_logo.png
    - assets/images/img_bot_second.png
    - assets/images/img_bot_third.png
    - assets/images/splash_icon.png
    - assets/images/user_icon.png
    - assets/images/arrow_right_icon.png
    - assets/images/arrow_right_green.png
    - assets/images/logo_white.png
    - assets/images/logo_blue.png
    - assets/images/img_bot_first_blue.png
    - assets/images/img_bot_back.png
    - assets/images/img_bot_third_blue.png
    - assets/images/img_bot_second_blue.png
    - assets/images/arrow_right_white.png
    - assets/images/chat_back.png
